language: node_js #設置語言

node_js: stable #設置相應的版本

cache:
  apt: true
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - xiaoyuechuanz@163.com
    on_success: change
    on_failure: always

before_install:
  - export TZ='Asia/Shanghai'
  - npm install hexo-cli -g
  - chmod +x ./publish.sh

install:
  - npm install

script:
  - hexo clean
  - hexo generate

after_script:
  - ./publish.sh

branches:
  only:
    - blog
env:
  global:
    - GH_REF: github.com/yuechuanx/yuechuanx.github.io # 设置 github 项目仓库地址
    - GH_username: yuechuanx # 设置 github 用户名
    - GH_useremail: xiaoyuechuanz@163.com
